server:
  port: 8080
spring:
  devtools:
    restart:
      additional-paths: src/main/java

      enabled: true
  resources:
    chain:
      strategy:
        content:
          enabled: true
          paths: /**

  datasource:
    name: root
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=UTF-8&useSSL=false
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
      suffix: .html
      prefix: classpath:/static/page/html/
      mode: HTML
      encoding: UTF-8
      cache: false

#配置日志
logging:
  level:
    #不同目录下的日志可配置不同级别
    org.springfromework.web: INFO
    org.hibernate: ERROR
  #采用相对路径方式将日志文件输出到【log/myspringboot.log】
  #采用绝对路径方式将日志文件输出到【/Users/wang/Downloads/myspringboot.log】
  #file: /Users/wang/Downloads/myspringboot.log
  file: D:/log/myspringboot.log
